admin_mall_help_index:
  path: /admin/mall/help/index
  controller: Eduxplus\EduxBundle\Controller\Mall\HelpController::indexAction
admin_mall_help_view:
  path: /admin/mall/help/view/{id}
  controller: Eduxplus\EduxBundle\Controller\Mall\HelpController::viewAction
admin_mall_help_add:
  path: /admin/mall/help/add
  controller: Eduxplus\EduxBundle\Controller\Mall\HelpController::addAction
admin_api_mall_help_add:
  path: /admin/mall/help/add/do
  controller: Eduxplus\EduxBundle\Controller\Mall\HelpController::addDoAction
admin_mall_help_edit:
  path: /admin/mall/help/edit/{id}
  controller: Eduxplus\EduxBundle\Controller\Mall\HelpController::editAction
admin_api_mall_help_edit:
  path: /admin/mall/help/edit/do/{id}
  controller: Eduxplus\EduxBundle\Controller\Mall\HelpController::editDoAction
admin_api_mall_help_delete:
  path: /admin/mall/help/delete/do/{id}
  controller: Eduxplus\EduxBundle\Controller\Mall\HelpController::deleteDoAction
admin_api_mall_help_bathdelete:
  path: /admin/mall/help/bathdelete/do
  controller: Eduxplus\EduxBundle\Controller\Mall\HelpController::bathdeleteDoAction
admin_api_mall_help_switchStatus:
  path: /admin/mall/help/switchStatus/do/{id}
  controller: Eduxplus\EduxBundle\Controller\Mall\HelpController::switchStatusAction
