admin_mall_coupon_index:
  path: /admin/mall/coupon/index
  controller: Eduxplus\CoreBundle\Controller\Mall\CouponController::indexAction
admin_mall_coupon_add:
  path: /admin/mall/coupon/add
  controller: Eduxplus\CoreBundle\Controller\Mall\CouponController::addAction
admin_api_mall_coupon_add:
  path: /admin/mall/coupon/add/do
  controller: Eduxplus\CoreBundle\Controller\Mall\CouponController::addDoAction
admin_mall_coupon_edit:
  path: /admin/mall/coupon/edit/{id}
  controller: Eduxplus\CoreBundle\Controller\Mall\CouponController::editAction
admin_api_mall_coupon_edit:
  path: /admin/mall/coupon/edit/do/{id}
  controller: Eduxplus\CoreBundle\Controller\Mall\CouponController::editDoAction
admin_api_mall_coupon_delete:
  path: /admin/mall/coupon/delete/do/{id}
  controller: Eduxplus\CoreBundle\Controller\Mall\CouponController::deleteDoAction
admin_api_mall_coupon_bathdelete:
  path: /admin/mall/coupon/bathdelete/do
  controller: Eduxplus\CoreBundle\Controller\Mall\CouponController::bathdeleteDoAction
admin_api_mall_coupon_switchStatus:
  path: /admin/mall/coupon/switchStatus/do/{id}
  controller: Eduxplus\CoreBundle\Controller\Mall\CouponController::switchStatusAction
admin_mall_couponsub_index:
  path: /admin/mall/couponsub/index/{id}
  controller: Eduxplus\CoreBundle\Controller\Mall\CouponController::subAction
admin_mall_couponsub_create:
  path: /admin/mall/couponsub/create/{id}
  controller: Eduxplus\CoreBundle\Controller\Mall\CouponController::subCouponCreateAction
admin_mall_couponsub_export:
  path: /admin/mall/couponsub/export/{id}
  controller: Eduxplus\CoreBundle\Controller\Mall\CouponController::subexportAction
