admin_mall_help_index:
  path: /admin/mall/help/index
  controller: Eduxplus/CoreBundle/Controller/Mall/HelpController::indexAction
admin_mall_help_view:
  path: /admin/mall/help/view/{id}
  controller: Eduxplus/CoreBundle/Controller/Mall/HelpController::viewAction
admin_mall_help_add:
  path: /admin/mall/help/add
  controller: Eduxplus/CoreBundle/Controller/Mall/HelpController::addAction
admin_api_mall_help_add:
  path: /admin/mall/help/add/do
  controller: Eduxplus/CoreBundle/Controller/Mall/HelpController::addDoAction
admin_mall_help_edit:
  path: /admin/mall/help/edit/{id}
  controller: Eduxplus/CoreBundle/Controller/Mall/HelpController::editAction
admin_api_mall_help_edit:
  path: /admin/mall/help/edit/do/{id}
  controller: Eduxplus/CoreBundle/Controller/Mall/HelpController::editDoAction
admin_api_mall_help_delete:
  path: /admin/mall/help/delete/do/{id}
  controller: Eduxplus/CoreBundle/Controller/Mall/HelpController::deleteDoAction
admin_api_mall_help_bathdelete:
  path: /admin/mall/help/bathdelete/do
  controller: Eduxplus/CoreBundle/Controller/Mall/HelpController::bathdeleteDoAction
admin_api_mall_help_switchStatus:
  path: /admin/mall/help/switchStatus/do/{id}
  controller: Eduxplus/CoreBundle/Controller/Mall/HelpController::switchStatusAction
