eduxplus_api_index_index:
  path: /apiauto{params}
  controller: Eduxplus\ApiBundle\Controller\IndexController::indexAction
  requirements: 
    params: .+
api_index_test:
  path: /api/test
  controller: Eduxplus\ApiBundle\Controller\IndexController::test
