admin_teach_agreement_index:
  path: /admin/teach/agreement/index
  controller: Eduxplus/CoreBundle/Controller/Teach/AgreementController::indexAction
admin_teach_agreement_view:
  path: /admin/teach/agreement/view/{id}
  controller: Eduxplus/CoreBundle/Controller/Teach/AgreementController::viewAction
admin_teach_agreement_add:
  path: /admin/teach/agreement/add
  controller: Eduxplus/CoreBundle/Controller/Teach/AgreementController::addAction
admin_api_teach_agreement_add:
  path: /admin/teach/agreement/add/do
  controller: Eduxplus/CoreBundle/Controller/Teach/AgreementController::addDoAction
admin_teach_agreement_edit:
  path: /admin/teach/agreement/edit/{id}
  controller: Eduxplus/CoreBundle/Controller/Teach/AgreementController::editAction
admin_api_teach_agreement_edit:
  path: /admin/teach/agreement/edit/do/{id}
  controller: Eduxplus/CoreBundle/Controller/Teach/AgreementController::editDoAction
admin_api_teach_agreement_delete:
  path: /admin/teach/agreement/delete/do/{id}
  controller: Eduxplus/CoreBundle/Controller/Teach/AgreementController::deleteAction
admin_api_teach_agreement_bathdelete:
  path: /admin/teach/agreement/bathdelete/do
  controller: Eduxplus/CoreBundle/Controller/Teach/AgreementController::bathDeleteAction
