admin_teach_category_index:
  path: /admin/teach/category/index
  controller: Eduxplus/CoreBundle/Controller/Teach/CategoryController::indexAction
admin_api_teach_category_add:
  path: /admin/teach/category/add/do
  controller: Eduxplus/CoreBundle/Controller/Teach/CategoryController::addDoAction
admin_teach_category_edit:
  path: /admin/teach/category/edit/{id}
  controller: Eduxplus/CoreBundle/Controller/Teach/CategoryController::editAction
admin_api_teach_category_edit:
  path: /admin/teach/category/edit/do/{id}
  controller: Eduxplus/CoreBundle/Controller/Teach/CategoryController::editDoAction
admin_api_teach_category_delete:
  path: /admin/teach/category/delete/do/{id}
  controller: Eduxplus/CoreBundle/Controller/Teach/CategoryController::deleteDoAction
admin_api_teach_category_updateSort:
  path: /admin/teach/category/updateSort/do
  controller: Eduxplus/CoreBundle/Controller/Teach/CategoryController::updateSortAction
