doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes:  "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        query_cache_driver:
            type: pool
            pool: doctrine.second_level_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.second_level_cache_pool
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        second_level_cache:
            region_cache_driver:
                type: pool
                pool: doctrine.second_level_cache_pool
            log_enabled: true
            enabled: true
            region_lifetime: 3600
