# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_listener:
        array_normalizer:
            service: fos_rest.normalizer.camel_keys
            forms: true
        decoders:
            json: fos_rest.decoder.jsontoform

    view:
        view_response_listener:  'force'
        empty_content: 200

    exception:
        codes:
            Eduxplus\CoreBundle\Exception\LoginExpiredException: 408 #登录过期
            Eduxplus\CoreBundle\Exception\NeedLoginException: 409 #需要登录
        messages:

    format_listener:
        enabled: true
        rules:
             - { path: '/api/',prefer_extension: true,fallback_format: 'json',priorities: ['json'] }
             - { path: '/do[/]?',prefer_extension: true,fallback_format: 'json',priorities: ['json'] }
             - { path: '^/admin',prefer_extension: true,fallback_format: 'html',priorities: ['html'] }
             - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }

    versioning:
        enabled: true
        guessing_order: [query, custom_header]  # X-Accept-Version header

    unauthorized_challenge: "Basic realm=\"Restricted Area\""
