framework:
    cache: 
        app: cache.adapter.redis
        default_redis_provider: snc_redis.default
        pools: 
            doctrine.second_level_cache_pool: 
                adapter: cache.app
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 604800
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true
    assets:
      version: 'v20200702'
