framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true
    cache:
        app: cache.adapter.redis
        default_redis_provider: snc_redis.default

    session:
        handler_id: snc_redis.session.handler
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 604800

    php_errors:
        log: true

    assets:
      version: 'v20200327'
