security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: 'auto'
      cost:      15

  providers:
    app_user_provider:
      entity:
        class: Eduxplus\CoreBundle\Entity\BaseUser
        property: id

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    admin:
      pattern: ^/admin
      lazy: true
      provider: app_user_provider
      custom_authenticators:
          - Eduxplus\CoreBundle\Security\PasswordLoginAuthenticator
      entry_point: Eduxplus\CoreBundle\Security\PasswordLoginAuthenticator
      logout:
        path: admin_logout
        target: /admin/login
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800 # 1 week in seconds
        path: /

    api:
      pattern: ^/api
      stateless: true
      lazy: true
      provider: app_user_provider
      custom_authenticators:
          - Eduxplus\ApiBundle\Security\TokenAuthenticator
          - Eduxplus\ApiBundle\Security\MobileAuthenticator
      entry_point: Eduxplus\ApiBundle\Security\TokenAuthenticator

    website:
      pattern: ^/
      lazy: true
      custom_authenticators:
          - Eduxplus\WebsiteBundle\Security\MobileAuthenticator
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 2592000 # 30 days in seconds
        path: /
      logout:
        path: app_logout
        success_handler: Eduxplus\WebsiteBundle\Security\LogoutSuccessHandle


  access_control:
    - { path: ^/admin/login$, allow_if: "not is_granted('ROLE_USER')" }
    - { path: ^/admin, roles: ROLE_USER }
    - { path: /my[/]?, roles: ROLE_USER }
