security:
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    admin:
      pattern: ^/admin
      anonymous: lazy
      provider: app_user_provider
      guard:
        authenticators:
          - Eduxplus\CoreBundle\Security\PasswordLoginAuthenticator
        entry_point: Eduxplus\CoreBundle\Security\PasswordLoginAuthenticator
      logout:
        path: admin_logout
        target: /admin/login
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800 # 1 week in seconds
        path: /

    api:
      pattern: ^/api
      stateless: true
      anonymous: lazy
      provider: app_user_provider
      guard:
        authenticators:
          - Eduxplus\ApiBundle\Security\TokenAuthenticator
          - Eduxplus\ApiBundle\Security\MobileAuthenticator
        entry_point: Eduxplus\ApiBundle\Security\TokenAuthenticator

    app:
      pattern: ^/
      anonymous: lazy
      guard:
        authenticators:
          - Eduxplus\WebsiteBundle\Security\MobileAuthenticator
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 2592000 # 30 days in seconds
        path: /
      logout:
        path: app_logout
        success_handler: Eduxplus\WebsiteBundle\Security\LogoutSuccessHandle


  access_control:
    - { path: "^/admin/login$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: "^/admin", roles: ROLE_USER }
    - { path: "/my[/]?", roles: ROLE_USER }
