snc_redis:
  clients:
      default:
          type: phpredis
          alias: default
          dsn: "redis://%redis_host%/1"
          logging: '%kernel.debug%'
          options:
            prefix: exp_
            connection_timeout: 10
            read_write_timeout: 30

      cache:
          type: phpredis
          alias: cache
          dsn: "redis://%redis_host%/2"
          logging: '%kernel.debug%'
          options:
              prefix: exp_cache_
              connection_timeout: 10
              read_write_timeout: 30

      session:
          type: phpredis
          alias: session
          dsn: "redis://%redis_host%/3"
          logging: '%kernel.debug%'
          options:
            prefix: exp_session_
            connection_timeout: 10
            read_write_timeout: 30

      persistence:
          type: phpredis
          alias: persistence
          dsn: "redis://%redis_host%/4"
          logging: '%kernel.debug%'
          options:
            prefix: exp_persistence_
            connection_timeout: 60
            read_write_timeout: 30
