twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    paths:
      "%kernel.project_dir%/src/Bundle/AdminBundle/Resources/templates": "AdminBundle"
      "%kernel.project_dir%/src/Bundle/AdminBundle/Lib/Grid/templates": "Grid"
      "%kernel.project_dir%/src/Bundle/AdminBundle/Lib/Form/templates": "Form"
      "%kernel.project_dir%/src/Bundle/AdminBundle/Lib/View/templates": "View"
      "%kernel.project_dir%/src/Bundle/AppBundle/Resources/templates/default": "AppBundle"
