zenstruck_schedule:
  without_overlapping_lock_factory: lock.scheduler.factory
  single_server_lock_factory: lock.scheduler.factory
  timezone: Asia/Shanghai

  messenger:
    enabled: true
    message_bus: command.bus
  schedule_extensions:
    environments:         [dev, prod, staging]
    on_single_server:
      enabled: true
      ttl: 3600
  tasks:
    - task: core:test
      frequency: '* * * * *'
      description: schedule run test
      without_overlapping: ~ #避免重复执行
    - task: messenger:consume async failed_default --time-limit=600
      frequency: '* * * * *'
      description: consuming Messages
      without_overlapping: ~ #避免重复执行
