zenstruck_schedule:
  without_overlapping_lock_factory: lock.scheduler.factory
  single_server_lock_factory: lock.scheduler.factory
  timezone: Asia/Shanghai

  messenger:
    enabled: true
    message_bus: command.bus
  schedule_extensions:
    environments:         [dev, prod, staging]
    on_single_server:
      enabled: true
      ttl: 3600
  tasks:
    - task: core:gen:dir
      frequency: '* * * * *'
      description: gen dir
