version: '3.7'
services:
    db:
        container_name: db
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: Root_123456
            MYSQL_DATABASE: eduxplus
            MYSQL_USER: root
            MYSQL_PASSWORD: Root_123456
        networks:
            - db
    redis:
        container_name: redis
        image: redis
        ports:
            - "6378:6379"
        networks:
            - redis
    php:
        container_name: php-fpm
        build: ./docs/docker/php-fpm
        ports:
            - "9001:9001"
        volumes:
            - ./:/var/www/symfony:cached
        depends_on:
            - db
            - redis
        networks:
            - redis
            - db
            - php
    nginx:
        container_name: nginx
        build: ./docs/docker/nginx
        ports:
            - "81:80"
        depends_on:
            - php
        networks:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./:/var/www/symfony:cached
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        environment:
            discovery.type: "single-node"
        ports:
            - "9200:9200"
        networks:
            elk_stack:
                aliases:
                    - "elasticsearch"
    logstash:
        container_name: logstash
        image: docker.elastic.co/logstash/logstash:7.4.2
        depends_on:
            - elasticsearch
        volumes:
            - ./elk/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:cached
            - ./elk/logstash/conf.d:/etc/logstash/conf.d:cached
            - ./logs/nginx:/var/log/nginx:cached
        networks:
            - elk_stack
    kibana:
        container_name: kibana
        depends_on:
            - elasticsearch
        image: docker.elastic.co/kibana/kibana:7.4.2
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        networks:
            - elk_stack
        ports:
            - "82:5601"

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
networks:
    db:
    redis:
    php:
    elk_stack:

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
