version: '3.7'
services:
    db:
        container_name: db
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: eduxplus
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        networks:
            - db
    redis:
        container_name: redis
        image: redis
        ports:
            - "6378:6379"
        networks:
            - redis
    php:
        container_name: php-fpm
        build: ./docs/docker/php-fpm
        ports:
            - "9001:9001"
        volumes:
            - ./:/var/www/symfony:cached
        depends_on:
            - db
            - redis
        networks:
            - redis
            - db
            - php
    nginx:
        container_name: nginx
        build: ./docs/docker/nginx
        ports:
            - "81:80"
        depends_on:
            - php
        networks:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./:/var/www/symfony:cached
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        environment:
            discovery.type: "single-node"
        ports:
            - "9200:9200"
        networks:
            es:
                aliases:
                    - "elasticsearch"
networks:
    db:
    redis:
    php:
    es:

