# WebsiteBundle.Controllers:
#   resource: ../../Controller/
#   type: annotation
#   prefix: /

user:
  resource: "./routes/user.yaml"

search:
  resource: "./routes/search.yaml"

order:
  resource: "./routes/order.yaml"


detail:
  resource: "./routes/detail.yaml"
glob:
  resource: "./routes/glob.yaml"
help:
  resource: "./routes/help.yaml"
index:
  resource: "./routes/index.yaml"
learn:
  resource: "./routes/learn.yaml"
news:
  resource: "./routes/news.yaml"
