# WebsiteBundle.Controllers:
#   resource: ../../Controller/
#   type: annotation
#   prefix: /

user:
  resource: "./routes/user.yaml"

search:
  resource: "./routes/search.yaml"

order:
  resource: "./routes/order.yaml"


