# WebsiteBundle.Controllers:
#   resource: ../../Controller/
#   type: annotation
#   prefix: /

website_detail:
  resource: "./routes/detail.yaml"
website_glob:
  resource: "./routes/glob.yaml"
website_help:
  resource: "./routes/help.yaml"
website_index:
  resource: "./routes/index.yaml"
website_learn:
  resource: "./routes/learn.yaml"
website_news:
  resource: "./routes/news.yaml"
website_order:
  resource: "./routes/order.yaml"
website_search:
  resource: "./routes/search.yaml"
website_user:
  resource: "./routes/user.yaml"
