parameters:
services:
    admin.getProp.twig.extension:
        class: App\Bundle\AdminBundle\Twig\GetPropExtension
        tags:
            - { name: twig.extension }
    admin.arrayGet.twig.extension:
        class: App\Bundle\AdminBundle\Twig\ArrayGetExtension
        tags:
            - { name: twig.extension }
