admin_cms_help_category_index:
  path: /admin/cms/help/category/index
  controller: Eduxplus\CmsBundle\Controller\Admin\HelpCategoryController::indexAction
admin_api_cms_help_category_add:
  path: /admin/cms/help/category/add/do
  controller: Eduxplus\CmsBundle\Controller\Admin\HelpCategoryController::addDoAction
admin_cms_help_category_edit:
  path: /admin/cms/help/category/edit/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\HelpCategoryController::editAction
admin_api_cms_help_category_edit:
  path: /admin/cms/help/category/edit/do/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\HelpCategoryController::editDoAction
admin_api_cms_help_category_delete:
  path: /admin/cms/help/category/delete/do/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\HelpCategoryController::deleteDoAction
admin_api_cms_help_category_updateSort:
  path: /admin/cms/help/category/updateSort/do
  controller: Eduxplus\CmsBundle\Controller\Admin\HelpCategoryController::updateSortAction
