admin_cms_news_index:
  path: /admin/cms/news/index
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsController::indexAction
admin_cms_news_view:
  path: /admin/cms/news/view/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsController::viewAction
admin_cms_news_add:
  path: /admin/cms/news/add
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsController::addAction
admin_api_cms_news_add:
  path: /admin/cms/news/add/do
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsController::addDoAction
admin_cms_news_edit:
  path: /admin/cms/news/edit/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsController::editAction
admin_api_cms_news_edit:
  path: /admin/cms/news/edit/do/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsController::editDoAction
admin_api_cms_news_delete:
  path: /admin/cms/news/delete/do/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsController::deleteDoAction
admin_api_cms_news_bathdelete:
  path: /admin/cms/news/bathdelete/do
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsController::bathdeleteDoAction
admin_api_cms_news_switchStatus:
  path: /admin/cms/news/switchStatus/do/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsController::switchStatusAction
