admin_cms_news_category_index:
  path: /admin/cms/news/category/index
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsCategoryController::indexAction
admin_api_cms_news_category_add:
  path: /admin/cms/news/category/add/do
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsCategoryController::addDoAction
admin_cms_news_category_edit:
  path: /admin/cms/news/category/edit/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsCategoryController::editAction
admin_api_cms_news_category_edit:
  path: /admin/cms/news/category/edit/do/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsCategoryController::editDoAction
admin_api_cms_news_category_delete:
  path: /admin/cms/news/category/delete/do/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsCategoryController::deleteDoAction
admin_api_cms_news_category_updateSort:
  path: /admin/cms/news/category/updateSort/do
  controller: Eduxplus\CmsBundle\Controller\Admin\NewsCategoryController::updateSortAction
