admin_cms_page_index:
  path: /admin/cms/page/index
  controller: Eduxplus\CmsBundle\Controller\Admin\PageController::indexAction
admin_cms_page_add:
  path: /admin/cms/page/add
  controller: Eduxplus\CmsBundle\Controller\Admin\PageController::addAction
admin_api_cms_page_add:
  path: /admin/cms/page/add/do
  controller: Eduxplus\CmsBundle\Controller\Admin\PageController::addDoAction
admin_cms_page_view:
  path: /admin/cms/page/view/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\PageController::viewAction
admin_cms_page_edit:
  path: /admin/cms/page/edit/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\PageController::editAction
admin_api_cms_page_edit:
  path: /admin/cms/page/edit/do/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\PageController::editDoAction
admin_api_cms_page_delete:
  path: /admin/cms/page/delete/do/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\PageController::deleteDoAction
admin_api_cms_page_bathdelete:
  path: /admin/cms/page/bathdelete/do
  controller: Eduxplus\CmsBundle\Controller\Admin\PageController::bathDeleteDoAction
admin_api_cms_page_switchStatus:
  path: /admin/cms/page/switchStatus/do/{id}
  controller: Eduxplus\CmsBundle\Controller\Admin\PageController::switchStatusAction
