# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_listener:
        array_normalizer:
            service: fos_rest.normalizer.camel_keys
            forms: true
        decoders:
            json: fos_rest.decoder.jsontoform

    view:
        view_response_listener:  'force'
        empty_content: 200

    exception:
#        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            Doctrine\ORM\EntityNotFoundException: 404
            \LogicException: 400
            \DomainException: 400
            \InvalidArgumentException: 400
            Symfony\Component\Security\Core\Exception\AuthenticationException: 403
            Symfony\Component\Security\Core\Exception\AccessDeniedException: 403
        messages:
            Doctrine\ORM\EntityNotFoundException: true
            \LogicException: true
            \DomainException: true
            \InvalidArgumentException: true
            Symfony\Component\Security\Core\Exception\AuthenticationException: true
            Symfony\Component\Security\Core\Exception\AccessDeniedException: true

    format_listener:
        enabled: true
        rules:
             - { path: '^/app/api',prefer_extension: true,fallback_format: 'json',priorities: ['json'] }
             - { path: '^/admin/api',prefer_extension: true,fallback_format: 'json',priorities: ['json'] }
             - { path: '^/admin',prefer_extension: true,fallback_format: 'html',priorities: ['html'] }

    versioning:
        enabled: true
        guessing_order: [query, custom_header]  # X-Accept-Version header

    unauthorized_challenge: "Basic realm=\"Restricted Area\""

    access_denied_listener:
        json: true
