security:
    encoders:
        App\Entity\BaseUser:
         algorithm: bcrypt

    providers:
        api_token:
            entity:
                class: App\Entity\BaseUser
                property: uuid
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
          pattern:  ^/api
          stateless: true
          anonymous: true
          provider: api_token
          guard:
              authenticators:
                  - App\Bundle\ApiBundle\Security\TokenAuthenticator

        admin:
          pattern:  ^/admin
          anonymous: lazy
          provider: api_token
          guard:
            authenticators:
                - App\Bundle\AdminBundle\Security\AdminLoginAuthenticator
          logout:
            path: admin_logout
            target: /admin/login
          remember_me:
            secret:   '%kernel.secret%'
            lifetime: 604800 # 1 week in seconds
            path:     /

