security:
    encoders:
        App\Entity\BaseUser: bcrypt
    providers:
        database:
            entity:
                class: App\Entity\BaseUser
                property: mobile
#       lexik_jwt:
#       class: App\Entity\BaseUser
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
          pattern:  ^/api
          stateless: true
          anonymous: true
          json_login:
              check_path: /api/login
              success_handler: lexik_jwt_authentication.handler.authentication_success
              failure_handler: lexik_jwt_authentication.handler.authentication_failure
              username_path: mobile
              password_path: password
          guard:
              authenticators:
                  - App\Security\TokenAuthenticator
          user_checker: App\Security\UserEnabledChecker

        api_doc:
              pattern:  ^/api/doc
              stateless: true
              anonymous: true

    role_hierarchy:
         ROLE_ADMIN: ROLE_USER

    access_control:
         - { path: '^/admin', roles: [ROLE_ADMIN] }
         - { path: '^/api/test', roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: '^/api/doc', roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: '^/api', roles: IS_AUTHENTICATED_FULLY }

