security:
    encoders:
        App\Entity\BaseUser:
         algorithm: bcrypt

    providers:
        app_token:
            entity:
                class: App\Entity\BaseUser
                property: mobile
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        appApi:
          pattern:  ^/appApi
          stateless: true
          anonymous: true
          provider: app_token
          guard:
              authenticators:
                  - app.token_authenticator
#          user_checker: App\Security\UserEnabledChecker

        api_doc:
          pattern:  ^/api/doc$
          stateless: true
          anonymous: true

    role_hierarchy:
         ROLE_ADMIN: ROLE_USER

    access_control:
         - { path: '^/api/doc', roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: '^/appApi/test', roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: '^/appApi/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: '^/appApi/register', roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: '^/appApi', roles: IS_AUTHENTICATED_FULLY }
         - { path: '^/admApi', roles: [ROLE_ADMIN] }

