security:
    encoders:
        App\Entity\BaseUser:
         algorithm: bcrypt

    providers:
        api_token:
            entity:
                class: App\Entity\BaseUser
                property: mobile
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        appApi:
          pattern:  ^/app/api
          stateless: true
          anonymous: true
          provider: api_token
          guard:
              authenticators:
                  - api.token_authenticator

        adminApi:
          pattern:  ^/admin/api
          stateless: true
          anonymous: true
          provider: api_token
          guard:
              authenticators:
                  - api.token_authenticator
          user_checker: App\Security\UserEnabledChecker

        admin:
          pattern:  ^/admin
          anonymous: lazy
          provider: api_token
          guard:
            authenticators:
                - App\Security\AdminLoginAuthenticator
          logout:
            path: admin_logout
            target: /admin/login
          remember_me:
            secret:   '%kernel.secret%'
            lifetime: 604800 # 1 week in seconds
            path:     /

    role_hierarchy:
         ROLE_ADMIN: ROLE_USER

    access_control:
         - { path: '^/app/api/test', roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: '^/app/api/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: '^/app/api/register', roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: '^/app/api', roles: IS_AUTHENTICATED_FULLY }
         - { path: '^/admin/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: '^/admin', roles: [ROLE_ADMIN] }

