admin_teach_category_index:
  path: /admin/teach/category/index
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CategoryController::indexAction
admin_api_teach_category_add:
  path: /admin/teach/category/add/do
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CategoryController::addDoAction
admin_teach_category_edit:
  path: /admin/teach/category/edit/{id}
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CategoryController::editAction
admin_api_teach_category_edit:
  path: /admin/teach/category/edit/do/{id}
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CategoryController::editDoAction
admin_api_teach_category_delete:
  path: /admin/teach/category/delete/do/{id}
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CategoryController::deleteDoAction
admin_api_teach_category_updateSort:
  path: /admin/teach/category/updateSort/do
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CategoryController::updateSortAction
