admin_teach_course_index:
  path: /admin/teach/course/index
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CourseController::indexAction
admin_teach_course_add:
  path: /admin/teach/course/add
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CourseController::addAction
admin_api_teach_course_add:
  path: /admin/teach/course/add/do
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CourseController::addDoAction
admin_teach_course_edit:
  path: /admin/teach/course/edit/{id}
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CourseController::editAction
admin_api_teach_course_edit:
  path: /admin/teach/course/edit/do/{id}
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CourseController::editDoAction
admin_api_teach_course_delete:
  path: /admin/teach/course/delete/do/{id}
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CourseController::deleteDoAction
admin_api_teach_course_bathdelete:
  path: /admin/teach/course/bathdelete/do
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CourseController::bathDeleteDoAction
admin_api_teach_course_switchStatus:
  path: /admin/teach/course/switchStatus/do/{id}
  controller: Eduxplus\EduxBundle\Controller\Admin\Teach\CourseController::switchStatusAction
