controllers:
    resource: ../../src/Controller/
    type: annotation

adminBundleControllers:
    resource: ../../src/Bundle/AdminBundle/Controller/
    type: annotation
    prefix: /admin

kernel:
    resource: ../../src/Kernel.php
    type: annotation
