adminBundle.Controllers:
    resource: ../../src/Bundle/AdminBundle/Controller/
    type: annotation
    prefix: /admin

ApiBundle.Controllers:
    resource: ../../src/Bundle/ApiBundle/Controller/
    type: annotation
    prefix: /api
    
AppBundle.Controllers:
    resource: ../../src/Bundle/AppBundle/Controller/
    type: annotation
    prefix: /

kernel:
    resource: ../../src/Kernel.php
    type: annotation
