parameters:
  centerBundle.app.name: "hello center1"

services:

#    App\Bundle\CenterBundle\EventListener\DatabaseActivitySubscriber:
#            tags:
#              - { name: 'doctrine.event_subscriber'}
