api_auth:
  resource: "./routes/auth.yaml"
api_glob:
  resource: "./routes/glob.yaml"
api_good:
  resource: "./routes/good.yaml"
api_home:
  resource: "./routes/home.yaml"
api_im:
  resource: "./routes/im.yaml"
api_index:
  resource: "./routes/index.yaml"
api_learn:
  resource: "./routes/learn.yaml"
api_user:
  resource: "./routes/user.yaml"
