imports:
    - { resource: 'parameters.yaml' }
services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
    App\:
       resource: '../src/*'
       exclude: '../src/**/{DependencyInjection,Migrations,Resources,Entity,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Bundle\:
        resource: '../src/Bundle/**/Controller'
        tags: ['controller.service_arguments']

    App\Bundle\CenterBundle\EventListener\DatabaseActivitySubscriber:
            tags:
              - { name: 'doctrine.event_subscriber'}
