imports:
    - { resource: '../src/Bundle/AppBundle/Resources/config/services.yaml' }
    - { resource: '../src/Bundle/ApiBundle/Resources/config/services.yaml' }
    - { resource: '../src/Bundle/AdminBundle/Resources/config/services.yaml' }

parameters:
    redis_host: '%env(REDIS_HOST)%'

services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    App\:
       resource: '%kernel.project_dir%/src/*'
       exclude: '%kernel.project_dir%/src/**/{DependencyInjection,Migrations,Resources,Twig,Entity,Tests,Kernel.php}'

    App\Bundle\:
        resource: '../src/Bundle/**/Controller'
        tags: ['controller.service_arguments']

    App\EventSubscriber\DatabaseActivitySubscriber:
        tags:
          - { name: 'doctrine.event_subscriber'}

    App\Bundle\AppBundle\Lib\Service\RedisService:
        lazy: true
        arguments:
            $redisCLient: '@snc_redis.default'
    storage.redis:
        alias: App\Bundle\AppBundle\Lib\Service\RedisService
        public: true

    App\Bundle\AppBundle\Lib\Service\CacheService:
        public: true
        lazy: true
        arguments:
            $cacheCLient: '@snc_redis.cache'
