imports:
    - { resource: '../src/Bundle/AppBundle/Resources/config/services.yaml' }
    - { resource: '../src/Bundle/ApiBundle/Resources/config/services.yaml' }
    - { resource: '../src/Bundle/AdminBundle/Resources/config/services.yaml' }
parameters:

services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    App\:
       resource: '%kernel.project_dir%/src/*'
       exclude: '%kernel.project_dir%/src/**/{DependencyInjection,Migrations,Resources,Entity,Tests,Kernel.php}'

    App\Bundle\:
        resource: '../src/Bundle/**/Controller'
        tags: ['controller.service_arguments']

    App\EventSubscriber\DatabaseActivitySubscriber:
        tags:
          - { name: 'doctrine.event_subscriber'}

    Redis:
      class: Predis\Client
      arguments:
        $parameters: '%env(REDIS_URL)%'
#        $options:
#            parameters:
#                password: '%env(REDIS_PWD)%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
      arguments:
          - '@Redis'
          - { prefix: '%env(REDIS_PREFIX)%' }
