edux_index:
  resource: "./routes/index.yaml"
edux_glob:
  resource: "./routes/glob.yaml"
edux_class:
  resource: "./routes/jw/class.yaml"
edux_school:
  resource: "./routes/jw/school.yaml"
edux_teacher:
  resource: "./routes/jw/teacher.yaml"
edux_banner:
  resource: "./routes/mall/banner.yaml"
edux_coupon:
  resource: "./routes/mall/coupon.yaml"
edux_goods:
  resource: "./routes/mall/goods.yaml"
edux_order:
  resource: "./routes/mall/order.yaml"
edux_pay:
  resource: "./routes/mall/pay.yaml"
edux_agreement:
  resource: "./routes/teach/agreement.yaml"
edux_category:
  resource: "./routes/teach/category.yaml"
edux_chapter:
  resource: "./routes/teach/chapter.yaml"
edux_course:
  resource: "./routes/teach/course.yaml"
edux_product:
  resource: "./routes/teach/product.yaml"
edux_studyplan:
  resource: "./routes/teach/studyplan.yaml"
