<?php
/**
 * @Author: kaihui.wang
 * @Contact  hpuwang@gmail.com
 * @Version: 1.0.0
 * @Date: 2020/3/4 11:47
 */

namespace App\Lib\Base;
use EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController;
use Psr\Log\LoggerInterface;

class BaseEsAdminController extends EasyAdminController
{
    /**
     * @var LoggerInterface
     */
    protected $logger;


    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    public function getParameter(string $name)
    {
        return parent::getParameter($name); // TODO: Change the autogenerated stub
    }

}
