doctrine:
    orm:
        query_cache_driver:
            type: pool
            pool: doctrine.second_level_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.second_level_cache_pool
#        metadata_cache_driver:
#            type: pool
#            pool: doctrine.second_level_cache_pool
        second_level_cache:
            region_cache_driver:
                type: pool
                pool: doctrine.second_level_cache_pool
            log_enabled: false
            enabled: true
            region_lifetime: 3600
