app_glob_recaptcha:
  path: /recaptcha/{type}
  controller: Eduxplus\WebsiteBundle\Controller\GlobController::recaptchaAction
app_glob_sendCaptcha:
  path: /do/sendCaptcha
  controller: Eduxplus\WebsiteBundle\Controller\GlobController::sendCaptchaAction
app_glob_upload:
  path: /glob/upload/do/{type}
  controller: Eduxplus\WebsiteBundle\Controller\GlobController::uploadAction
  defaults:  
     type: img
app_glob_pay_alipayCallback:
  path: /pay/alipayCallback
  controller: Eduxplus\WebsiteBundle\Controller\GlobController::alipayCallbackAction
app_glob_pay_wxpayCallback:
  path: /pay/wxpayCallback
  controller: Eduxplus\WebsiteBundle\Controller\GlobController::wxpayCallbackAction
