app_news:
  path: /news/{category}/{page}
  controller: Eduxplus/WebsiteBundle/Controller/NewsController::indexAction
  defaults:  
     category: 0 
     page: 1 
app_news_detail:
  path: /news_detail/{id}
  controller: Eduxplus/WebsiteBundle/Controller/NewsController::detailAction
