parameters:
    redis_host: '%env(REDIS_HOST)%'
    upload_dir: '%env(UPLOAD_DIR)%'
    secret: '%env(APP_SECRET)%'

services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
        bind:
            $adminUserMobile: '%env(ADMIN_USER_MOBILE)%'
            $adminUserPwd: '%env(ADMIN_USER_PWD)%'
            $secret: '%env(APP_SECRET)%'

    App\:
       resource: '%kernel.project_dir%/src/*'
       exclude: '%kernel.project_dir%/src/**/{DependencyInjection,Migrations,Resources,Twig,Entity,Tests,Kernel.php}'

    App\Bundle\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    snc_second_level_cache:
        class: '%snc_redis.doctrine_cache_phpredis.class%'
#        lazy: true
        arguments:
            - '@snc_redis.secondlevelcache'

    App\Bundle\RoutingLoader:
      tags: [routing.loader]
