parameters:
    redis_host: '%env(REDIS_HOST)%'
    upload_dir: '%env(UPLOAD_DIR)%'
    secret: '%env(APP_SECRET)%'
    messenger.consumer.name: '%env(MESSENGER_CONSUMER_NAME)%'

services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    App\:
       resource: '%kernel.project_dir%/src/*'
       exclude: '%kernel.project_dir%/src/**/{DependencyInjection,Migrations,Resources,Twig,Entity,Tests,Kernel.php}'

    App\Bundle\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
