adminlog:
  resource: "./routes/adminlog.yaml"
auth:
  resource: "./routes/auth.yaml"
glob:
  resource: "./routes/glob.yaml"
index:
  resource: "./routes/index.yaml"
menu:
  resource: "./routes/menu.yaml"
option:
  resource: "./routes/option.yaml"
role:
  resource: "./routes/role.yaml"
user:
  resource: "./routes/user.yaml"
