core_adminlog:
  resource: "./routes/adminlog.yaml"
core_auth:
  resource: "./routes/auth.yaml"
core_glob:
  resource: "./routes/glob.yaml"
core_index:
  resource: "./routes/index.yaml"
core_menu:
  resource: "./routes/menu.yaml"
core_option:
  resource: "./routes/option.yaml"
core_role:
  resource: "./routes/role.yaml"
core_user:
  resource: "./routes/user.yaml"
