parameters:
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
        bind:
            $adminUserMobile: '%env(ADMIN_USER_MOBILE)%'
            $adminUserPwd: '%env(ADMIN_USER_PWD)%'

    Eduxplus\CoreBundle\:
        resource: '../../../src/'
        exclude: '../../../src/**/{DependencyInjection,Migrations,Resources,Twig,Entity,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Eduxplus\CoreBundle\Controller\:
        resource: '../../../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    Eduxplus\CoreBundle\Lib\Base\BaseService:
        shared: true
        calls:
            - [ inject, [ "@doctrine","@serializer",
                          "@request_stack","@router.default",
                          "@parameter_bag","@property_accessor",
                          "@security.token_storage","@service_container","@security.helper","@monolog.logger"] ]

    base.service:
        alias: Eduxplus\CoreBundle\Lib\Base\BaseService

    Eduxplus\CoreBundle\Lib\Base\AdminBaseService:
        parent: base.service

    Eduxplus\CoreBundle\Lib\Base\ApiBaseService:
        parent: base.service

    Eduxplus\CoreBundle\Lib\Base\AppBaseService:
        parent: base.service

    Eduxplus\CoreBundle\Lib\Service\Base\:
        resource: '../../../src/Lib/Service/Base/*'
        parent: base.service

    Eduxplus\CoreBundle\Service\:
        resource: '../../../src/Service/*'
        parent: base.service


    Eduxplus\CoreBundle\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
            
    Eduxplus\CoreBundle\Twig\GetPropExtension:
        tags:
            - { name: twig.extension }

    Eduxplus\CoreBundle\Twig\IsAuthorizedExtension:
        tags:
            - { name: twig.extension }

    Eduxplus\CoreBundle\Lib\Service\RedisService:
        lazy: true
        arguments:
            $redisCLient: '@snc_redis.default'

    Eduxplus\CoreBundle\Lib\Service\CacheService:
        public: true
        lazy: true
        arguments:
            $cacheCLient: '@snc_redis.cache'

    Eduxplus\CoreBundle\Doctrine\Generator\SnowflakeGenerator:
        lazy: true
        arguments:
            $redisCLient: '@snc_redis.persistence'

    Eduxplus\CoreBundle\Twig\FuncExtension:
        tags: [ 'twig.extension' ]

    Eduxplus\CoreBundle\Twig\FiltersExtension:
        tags: [ 'twig.extension' ]
