parameters:
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Eduxplus\CoreBundle\:
        resource: '../../../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Eduxplus\CoreBundle\Controller\:
        resource: '../../../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    Eduxplus\CoreBundle\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
            -
    admin.getProp.twig.extension:
        class: Eduxplus\CoreBundle\Twig\GetPropExtension
        tags:
            - { name: twig.extension }

    admin.isAuthorized.twig.extension:
        class: Eduxplus\CoreBundle\Twig\IsAuthorizedExtension
        arguments: ['@Eduxplus\CoreBundle\Service\RoleService']
        tags:
            - { name: twig.extension }

    Eduxplus\CoreBundle\Lib\Service\RedisService:
        lazy: true
        arguments:
            $redisCLient: '@snc_redis.default'

    Eduxplus\CoreBundle\Lib\Service\CacheService:
        public: true
        lazy: true
        arguments:
            $cacheCLient: '@snc_redis.cache'

    Eduxplus\CoreBundle\Twig\FuncExtension:
        tags: [ 'twig.extension' ]

    Eduxplus\CoreBundle\Twig\FiltersExtension:
        tags: [ 'twig.extension' ]
