centerBundle.Controllers:
    resource: ../../src/Bundle/CenterBundle/Controller/
    type: annotation
    prefix: /center

adminBundle.Controllers:
    resource: ../../src/Bundle/AdminBundle/Controller/
    type: annotation
    prefix: /admin

appBundle.Controllers:
    resource: ../../src/Bundle/AppBundle/Controller/
    type: annotation
    prefix: /app

kernel:
    resource: ../../src/Kernel.php
    type: annotation
