centerBundle.Controllers:
    resource: ../../src/Bundle/CenterBundle/Controller/
    type: annotation
    prefix: /api/center

adminBundle.Controllers:
    resource: ../../src/Bundle/AdminBundle/Controller/
    type: annotation
    prefix: /api/adm

appBundle.Controllers:
    resource: ../../src/Bundle/AppBundle/Controller/
    type: annotation
    prefix: /api/app

kernel:
    resource: ../../src/Kernel.php
    type: annotation
