centerBundle.Controllers:
    resource: ../../src/Bundle/CenterBundle/Controller/
    type: annotation
    prefix: /center

adminBundle.Controllers:
    resource: ../../src/Bundle/AdminBundle/Controller/
    type: annotation
    prefix: /admin

ApiBundle.Controllers:
    resource: ../../src/Bundle/ApiBundle/Controller/
    type: annotation
    prefix: /api

kernel:
    resource: ../../src/Kernel.php
    type: annotation
