adminBundle.Controllers:
    resource: ../../src/Bundle/AdminBundle/Controller/
    type: annotation
    prefix: /admApi

appBundle.Controllers:
    resource: ../../src/Bundle/AppBundle/Controller/
    type: annotation
    prefix: /appApi

kernel:
    resource: ../../src/Kernel.php
    type: annotation
