adminBundle.Controllers:
    resource: ../../src/Bundle/AdminBundle/Controller/
    type: annotation
    prefix: /adm

appBundle.Controllers:
    resource: ../../src/Bundle/AppBundle/Controller/
    type: annotation
    prefix: /app

kernel:
    resource: ../../src/Kernel.php
    type: annotation
