qa_chapter:
  resource: "./routes/admin/chapter.yaml"
qa_chaptersub:
  resource: "./routes/admin/chaptersub.yaml"
qa_glob:
  resource: "./routes/admin/glob.yaml"
qa_mallgoods:
  resource: "./routes/admin/mallgoods.yaml"
qa_node:
  resource: "./routes/admin/node.yaml"
qa_test:
  resource: "./routes/admin/test.yaml"
qa_testsub:
  resource: "./routes/admin/testsub.yaml"
qa_index:
  resource: "./routes/app/index.yaml"
