QaBundle.Admin.Controllers:
    resource: ../../Controller/Admin/
    type: annotation
    prefix: /admin/qa

QaBundle.App.Controllers:
  resource: ../../Controller/App/
  type: annotation
  prefix: /qa
