imports:
    - { resource: 'parameters.yaml' }
services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
        bind:
            $projectDir: '%kernel.project_dir%' #项目路径
#            $nameKaihui: '@name.kaihui'
#    #bundle service 加载
    App\ExpCenterBundle\:
        resource: '../src/ExpCenterBundle/*'
        exclude: '../src/ExpCenterBundle/{DependencyInjection,Resources,Entity,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\ExpCenterBundle\Controller\:
        resource: '../src/ExpCenterBundle/Controller'
        tags: ['controller.service_arguments']

    App\Repository\BaseUserRepository:
        tags: ['doctrine.repository_service']

    name.wang:
        class: App\ExpCenterBundle\Lib\Name
        autowire: false
        public: true
        arguments:
            $name: 'wang'

