imports:
    - { resource: 'parameters.yaml' }
services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%' #项目路径
    #bundle service 加载
    App\CenterBundle\:
        resource: '../src/CenterBundle/*'
        exclude: '../src/CenterBundle/{DependencyInjection,Resources,Entity,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\CenterBundle\Controller\:
        resource: '../src/CenterBundle/Controller'
        tags: ['controller.service_arguments']

    name.wang:
        class: App\CenterBundle\Lib\Name
        autowire: false
              arguments:
                $name: 'wang'

    name.kaihui:
        class: App\CenterBundle\Lib\Name
        autowire: false
              arguments:
                $name: 'kaihui'
