admin_jw_teacher_index:
  path: /admin/jw/teacher/index
  controller: Eduxplus\EduxBundle\Controller\Admin\Jw\TeacherController::indexAction
admin_jw_teacher_add:
  path: /admin/jw/teacher/add
  controller: Eduxplus\EduxBundle\Controller\Admin\Jw\TeacherController::addAction
admin_api_jw_teacher_add:
  path: /admin/jw/teacher/add/do
  controller: Eduxplus\EduxBundle\Controller\Admin\Jw\TeacherController::addDoAction
admin_jw_teacher_view:
  path: /admin/jw/teacher/view/{id}
  controller: Eduxplus\EduxBundle\Controller\Admin\Jw\TeacherController::viewAction
admin_jw_teacher_edit:
  path: /admin/jw/teacher/edit/{id}
  controller: Eduxplus\EduxBundle\Controller\Admin\Jw\TeacherController::editAction
admin_api_jw_teacher_edit:
  path: /admin/jw/teacher/edit/do/{id}
  controller: Eduxplus\EduxBundle\Controller\Admin\Jw\TeacherController::editDoAction
admin_api_jw_teacher_delete:
  path: /admin/jw/teacher/delete/do/{id}
  controller: Eduxplus\EduxBundle\Controller\Admin\Jw\TeacherController::deleteAction
admin_api_jw_teacher_bathdelete:
  path: /admin/jw/teacher/bathdelete/do
  controller: Eduxplus\EduxBundle\Controller\Admin\Jw\TeacherController::bathdeleteAction
admin_api_jw_teacher_switchStatus:
  path: /admin/jw/teacher/switchStatus/do/{id}
  controller: Eduxplus\EduxBundle\Controller\Admin\Jw\TeacherController::switchStatusAction
