admin_index:
  path: /admin/
  controller: Eduxplus\CoreBundle\Controller\IndexController::indexAction
admin_mymenu:
  path: /admin/mymenu
  controller: Eduxplus\CoreBundle\Controller\IndexController::mymenuAction
