parameters:
services:
    admin.getProp.twig.extension:
        class: App\Bundle\AdminBundle\Twig\GetPropExtension
        tags:
            - { name: twig.extension }

    admin.isAuthorized.twig.extension:
        class: App\Bundle\AdminBundle\Twig\IsAuthorizedExtension
        arguments: ['@App\Bundle\AdminBundle\Service\RoleService']
        tags:
            - { name: twig.extension }
