qa_admin_test_sub_index:
  path: /admin/qa/test/sub/index/{id}
  controller: Eduxplus\QaBundle\Controller\Admin\TestSubController::indexAction
qa_admin_test_sub_mg:
  path: /admin/qa/test/sub/mg/{id}/{type}/{isFirst}
  controller: Eduxplus\QaBundle\Controller\Admin\TestSubController::mgAction
  defaults:  
     type: 0 
     isFirst: 1 
qa_admin_test_sub_do_mg:
  path: /admin/qa/test/sub/mg/do/{id}
  controller: Eduxplus\QaBundle\Controller\Admin\TestSubController::mgDoAction
qa_admin_test_sub_edit:
  path: /admin/qa/test/sub/edit/{id}
  controller: Eduxplus\QaBundle\Controller\Admin\TestSubController::editAction
qa_admin_test_sub_do_edit:
  path: /admin/qa/test/sub/edit/do/{id}
  controller: Eduxplus\QaBundle\Controller\Admin\TestSubController::editDoAction
qa_admin_test_sub_delete:
  path: /admin/qa/test/sub/delete/do/{id}
  controller: Eduxplus\QaBundle\Controller\Admin\TestSubController::deleteDoAction
qa_admin_test_sub_bathdelete:
  path: /admin/qa/test/sub/bathdelete/do
  controller: Eduxplus\QaBundle\Controller\Admin\TestSubController::bathdeleteDoAction
